// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/28 16:44:10
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/allja/Desktop/Workspace/AlrdManage/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/allja/Desktop/Workspace/AlrdManage/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/allja/Desktop/Workspace/AlrdManage/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/allja/Desktop/Workspace/AlrdManage/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/allja/Desktop/Workspace/AlrdManage/plugins/**/*.{js,ts,mjs}","C:/Users/allja/Desktop/Workspace/AlrdManage/composables/**/*.{js,ts,mjs}","C:/Users/allja/Desktop/Workspace/AlrdManage/utils/**/*.{js,ts,mjs}","C:/Users/allja/Desktop/Workspace/AlrdManage/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/allja/Desktop/Workspace/AlrdManage/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/allja/Desktop/Workspace/AlrdManage/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/allja/Desktop/Workspace/AlrdManage/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;